# -*- coding: utf-8 -*-
"""
Check whether card descriptions in 3.0 no cost (current) match their
GameEventListener bindings.

Reads: docs/CardDesc_GameEventListener_Check.txt (generated by Unity execute_code)
Outputs: docs/CardDesc_GameEventListener_Mismatch_Report.md
"""
import re
import os
from collections import defaultdict

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_PATH = os.path.join(PROJECT_ROOT, "docs", "CardDesc_GameEventListener_Check.txt")
OUTPUT_PATH = os.path.join(PROJECT_ROOT, "docs", "CardDesc_GameEventListener_Mismatch_Report.md")


def parse_log(path):
    cards = []
    with open(path, "r", encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("CARD|"):
                continue
            # CARD|name|path|cardDesc=...|listeners=...
            parts = line.split("|", 4)
            if len(parts) < 5:
                continue
            name = parts[1]
            asset_path = parts[2]
            rest = parts[4]
            # parts[3] = cardDesc=..., parts[4] = listeners=...
            desc_part = parts[3]
            listeners_part = rest
            if not desc_part.startswith("cardDesc="):
                continue
            desc = desc_part[len("cardDesc="):].replace("\\n", "\n").replace("\\r", "\r").replace("\\|", "|")
            listeners_str = listeners_part
            listeners = []
            if listeners_str:
                for entry in listeners_str.split(","):
                    entry = entry.strip()
                    if not entry:
                        continue
                    # Strip optional "listeners=" prefix that appears on the first entry
                    if entry.startswith("listeners="):
                        entry = entry[len("listeners="):]
                    listeners.append((entry, ""))
            cards.append({"name": name, "path": asset_path, "desc": desc, "listeners": listeners})
    return cards


# Mapping from Chinese description trigger keywords to expected GameEvent asset names.
# Order matters: more specific phrases first.
TRIGGER_PATTERNS = [
    # Specific non-self triggers first (before generic 被XXX / 揭晓 patterns)
    ("当敌方[诅咒]揭晓", ["OnHostileCurseRevealed", "OnEnemyCurseCardRevealed"]),
    ("当敌方[诅咒]获得力量", ["OnEnemyCurseCardGotPower"]),
    ("当友方被埋葬", ["OnFriendlyCardBuried"]),
    ("友方被埋葬", ["OnFriendlyCardBuried"]),
    ("当卡被埋葬", ["OnFriendlyCardBuried"]),  # GRAVE_KEEPER triggers on friendly buried
    ("当友方被去除", ["OnFriendlyCardExiled"]),
    ("友方被去除", ["OnFriendlyCardExiled"]),
    ("当敌人受到伤害", ["OnTheirPlayerTookDmg"]),
    ("敌人受到伤害", ["OnTheirPlayerTookDmg"]),
    ("当友方获得力量", ["OnFriendlyCardGotPower"]),
    ("敌人被揭晓", ["OnHostileCardRevealed", "OnHostileRevealed"]),
    # Self triggers and generic keywords
    ("揭晓时,消耗敌方[诅咒]", ["OnMeRevealed"]),
    ("揭晓时,消耗", ["OnMeRevealed"]),
    ("揭晓时,墓地每有", ["OnMeRevealed"]),
    ("揭晓时,敌方[诅咒]每有", ["OnMeRevealed"]),
    ("揭晓时,敌方[诅咒]力量", ["OnMeRevealed"]),
    ("揭晓时,本回合每置顶过", ["OnMeRevealed"]),
    ("揭晓时:造成", ["OnMeRevealed"]),
    ("揭晓时:", ["OnMeRevealed"]),
    ("揭晓:", ["OnMeRevealed"]),
    ("揭晓", ["OnMeRevealed"]),
    ("被置顶", ["OnMeStaged"]),
    ("被埋葬", ["OnMeBuried"]),
    ("获得力量时", ["OnMeGotStatusEffect", "OnMeGotPower"]),
    ("每揭晓", ["OnMeRevealed"]),
    ("洗牌后", ["AfterShuffle"]),
    ("卡位增加", ["OnMeBought"]),
    ("生命值上限增加", ["OnMeBought"]),
    ("无效果", []),
]


def extract_expected_events(segment):
    """Given one description segment, return set of expected GameEvent names."""
    expected = set()
    for keyword, events in TRIGGER_PATTERNS:
        if keyword in segment:
            expected.update(events)
            break
    return expected


def normalize_event_name(name):
    return name.lower()


def check_card(card):
    mismatches = []
    desc = card["desc"]
    # Split description into independent segments by ; or newline
    segments = re.split(r"[;\n]", desc)
    # Filter out empty listener entries (e.g. DUMMY card with no listeners)
    non_empty_listeners = [(e, t) for e, t in card["listeners"] if e]
    actual_event_names = set(normalize_event_name(e) for e, _ in non_empty_listeners)

    # For each segment, figure expected event
    for seg in segments:
        seg = seg.strip()
        if not seg:
            continue
        expected = extract_expected_events(seg)
        if not expected:
            # Could not identify trigger; skip if there are listeners (likely formatting)
            continue
        expected_norm = set(normalize_event_name(e) for e in expected)
        if not expected_norm.intersection(actual_event_names):
            # None of the expected events are actually bound
            mismatches.append({
                "segment": seg,
                "expected": sorted(expected),
                "actual": sorted(set(e for e, _ in non_empty_listeners)),
            })

    # Also flag listeners that have no matching description segment (orphan listeners)
    described_events = set()
    for seg in segments:
        seg = seg.strip()
        if not seg:
            continue
        described_events.update(normalize_event_name(e) for e in extract_expected_events(seg))

    orphan_listeners = []
    for event_name, target in non_empty_listeners:
        if normalize_event_name(event_name) not in described_events:
            orphan_listeners.append((event_name, target))

    return mismatches, orphan_listeners


def build_report(cards):
    lines = []
    lines.append("# 卡片描述与 GameEventListener 对应检查报告")
    lines.append("")
    lines.append("**检查范围**：`Assets/Prefabs/Cards/3.0 no cost (current)` 下全部卡片")
    lines.append("")
    lines.append("**检查逻辑**：")
    lines.append("1. 将 `cardDesc` 按 `;` 或换行拆分为独立触发段落。")
    lines.append("2. 根据段落中的中文关键词推断期望的 GameEvent（如 `揭晓时` → `OnMeRevealed`、`被埋葬` → `OnMeBuried` 等）。")
    lines.append("3. 对比卡片上实际挂载的 `GameEventListener` 所订阅的事件。")
    lines.append("4. 若某段落期望的事件未在 Listener 中出现，或 Listener 中的事件未被描述覆盖，则标记为问题。")
    lines.append("")

    issue_cards = []
    for card in cards:
        mismatches, orphans = check_card(card)
        if mismatches or orphans:
            issue_cards.append((card, mismatches, orphans))

    # Summary
    total = len(cards)
    ok = total - len(issue_cards)
    lines.append("## 摘要")
    lines.append("")
    lines.append("| 项目 | 数量 |")
    lines.append("|---|---|")
    lines.append("| 检查卡片总数 | " + str(total) + " |")
    lines.append("| 无问题 | " + str(ok) + " |")
    lines.append("| 存在疑似不匹配 | " + str(len(issue_cards)) + " |")
    lines.append("")

    if not issue_cards:
        lines.append("## 结果")
        lines.append("")
        lines.append("所有卡片的描述段落均能在 GameEventListener 中找到对应事件，未发现明显不匹配。")
        lines.append("")
        return "\n".join(lines)

    lines.append("## 疑似不匹配卡片")
    lines.append("")

    for idx, (card, mismatches, orphans) in enumerate(issue_cards, 1):
        lines.append("### " + str(idx) + ". " + card["name"])
        lines.append("")
        lines.append("**路径**：`" + card["path"] + "`")
        lines.append("")
        lines.append("**描述**：")
        lines.append("```")
        lines.append(card["desc"])
        lines.append("```")
        lines.append("")
        lines.append("**实际 Listener**：")
        if card["listeners"]:
            for event_name, target in card["listeners"]:
                lines.append("- `" + event_name + "` → `" + target + "`")
        else:
            lines.append("- 无")
        lines.append("")

        if mismatches:
            lines.append("**描述段落缺少对应 Listener**：")
            lines.append("")
            lines.append("| 描述段落 | 期望事件 | 实际事件 |")
            lines.append("|---|---|---|")
            for m in mismatches:
                lines.append("| " + m["segment"] + " | " + ", ".join(m["expected"]) + " | " + ", ".join(m["actual"]) + " |")
            lines.append("")

        if orphans:
            lines.append("**Listener 事件未被描述覆盖**：")
            lines.append("")
            for event_name, target in orphans:
                lines.append("- `" + event_name + "` → `" + target + "`")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("**注意**：本报告基于关键词匹配，部分语义特殊或表述省略的卡片可能需要人工复核。")
    lines.append("")
    return "\n".join(lines)


def main():
    cards = parse_log(INPUT_PATH)
    report = build_report(cards)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(report)
    print("Report written to:", OUTPUT_PATH)
    print("Cards checked:", len(cards))


if __name__ == "__main__":
    main()
