# -*- coding: utf-8 -*-
"""
Check whether card descriptions match the actual GameEventListener responses
(event -> CostNEffectContainer -> effect method bindings) in 3.0 no cost cards.

Reads: docs/CardDesc_Response_Check.txt (generated by Unity execute_code)
Outputs: docs/CardDesc_Response_Mismatch_Report.md
"""
import re
import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_PATH = os.path.join(PROJECT_ROOT, "docs", "CardDesc_Response_Check.txt")
OUTPUT_PATH = os.path.join(PROJECT_ROOT, "docs", "CardDesc_Response_Mismatch_Report.md")


def parse_log(path):
    cards = []
    with open(path, "r", encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("CARD|"):
                continue
            parts = line.split("|", 4)
            if len(parts) < 5:
                continue
            name = parts[1]
            asset_path = parts[2]
            full = parts[3] + "|" + parts[4]
            if "|bindings=" not in full:
                continue
            desc_part, after = full.split("|bindings=", 1)
            if not desc_part.startswith("cardDesc="):
                continue
            desc = desc_part[len("cardDesc="):].replace("\\n", "\n").replace("\\r", "\r").replace("\\|", "|")

            listeners = []
            # Match each listener binding block; container names may contain ']' so we anchor at the trailing ' costs=...]'.
            for m in re.finditer(r"\[LISTENER\s+(.+?)\s+costs=(.*?)\]", after):
                inner = m.group(1).strip()
                costs_text = m.group(2).strip()
                listener = {"event": "NONE", "container": "", "effects": [], "costs": parse_calls(costs_text)}
                # Parse key=value pairs. Values may contain spaces; split at spaces preceding known keys.
                tokens = re.split(r"\s+(?=(?:event|container|effects|costs)=)", inner)
                for token in tokens:
                    if "=" not in token:
                        continue
                    k, v = token.split("=", 1)
                    k = k.strip()
                    v = v.strip()
                    if k == "event":
                        listener["event"] = v
                    elif k == "container":
                        listener["container"] = v
                    elif k == "effects":
                        listener["effects"] = parse_calls(v)
                listeners.append(listener)
            cards.append({"name": name, "path": asset_path, "desc": desc, "listeners": listeners})
    return cards


def parse_calls(text):
    calls = []
    if not text:
        return calls
    # Match calls like: Full.Type.Name[, Assembly]->MethodName(0)
    # The type may contain a comma-prefixed assembly name; method is a simple identifier.
    pattern = re.compile(
        r"([A-Za-z_][A-Za-z0-9_.]*(?:,\s*[A-Za-z_][A-Za-z0-9_.-]*)*)\s*->\s*([A-Za-z_][A-Za-z0-9_]*)\s*\((-?\d+)\)"
    )
    for m in pattern.finditer(text):
        full_type = m.group(1).strip()
        # Strip assembly suffix and namespace, keep only class name
        type_name = full_type.split(",")[0].strip()
        type_name = type_name.split(".")[-1].strip()
        method = m.group(2).strip()
        arg = int(m.group(3))
        calls.append({"type": type_name, "method": method, "arg": arg})
    return calls


def strip_tags(text):
    return re.sub(r"</?[^>]+>", "", text)


# -----------------------------------------------------------------------------
# Effect category mapping
# -----------------------------------------------------------------------------

def method_categories(call):
    """Return list of semantic categories for a C# method call."""
    t = call["type"]
    m = call["method"]
    cats = []

    if t == "HPAlterEffect":
        if m.startswith("DecreaseTheirHp"):
            cats.append("DAMAGE_OPPONENT")
        elif m.startswith("DecreaseMyHp"):
            cats.append("DAMAGE_SELF")
        elif m.startswith("IncreaseTheirHp"):
            cats.append("HEAL_OPPONENT")
        elif m.startswith("IncreaseMyHp"):
            cats.append("HEAL_SELF")
    elif t == "BuryEffect":
        if m in ("BuryMyCards", "BuryAllMyCards", "BuryMyCardsWithTag", "BuryMyCards_BasedOnIntSO"):
            cats.append("BURY_FRIENDLY")
        elif m in ("BuryTheirCards", "BuryTheirCardsWithTag", "BuryTheirCards_BasedOnIntSO"):
            cats.append("BURY_HOSTILE")
        elif m == "BuryNextXCards":
            cats.append("BURY_NEXT")
        elif m == "BuryCardsWithTag":
            cats.append("BURY_TAG")
        elif m == "BurySelf":
            cats.append("BURY_SELF")
    elif t == "StageEffect":
        if m in ("StageSelf", "StageMyCards", "StageMyCards_BasedOnIntSO", "StageMyCardsWithTag",
                 "StageMyTokens", "StageAllFriendlyMinion"):
            cats.append("STAGE_FRIENDLY")
        elif m in ("StageTheirCardsWithTag", "StageTheirSpecificCard"):
            cats.append("STAGE_HOSTILE")
        elif m == "StageCardWithMostStatusEffect":
            cats.append("STAGE_MOST_STATUS")
    elif t == "CurseEffect":
        if m in ("EnhanceCurse", "EnhanceCurse_BasedOnIntSO", "EnhanceCurseWithCoefficient_BasedOnIntSO"):
            cats.append("ENHANCE_CURSE")
        elif m == "EnhanceFriendlyCurse":
            cats.append("ENHANCE_FRIENDLY_CURSE")
        elif m == "ConsumeHostileCursePower":
            cats.append("CONSUME_CURSE_POWER")
    elif t == "StatusEffectGiverEffect":
        if m.startswith("Give"):
            cats.append("GIVE_STATUS_EFFECT")
    elif t == "PowerReactionEffect":
        if m.startswith("Give"):
            cats.append("GIVE_STATUS_EFFECT")
    elif t == "StatusEffectAmplifierEffect":
        if m.startswith("Amplify"):
            cats.append("GIVE_STATUS_EFFECT")
    elif t == "ConsumeStatusEffect":
        if m.startswith("Consume"):
            cats.append("CONSUME_STATUS_EFFECT")
    elif t == "TransferStatusEffectEffect":
        if m.startswith("Transfer"):
            cats.append("TRANSFER_STATUS_EFFECT")
    elif t == "AddTempCard":
        if m in ("AddCardToMe", "AddSelfToMe"):
            cats.append("ADD_CARD_FRIENDLY")
        elif m in ("AddCardToThem", "AddSelfToThem"):
            cats.append("ADD_CARD_ENEMY")
        elif m == "CopyEnemyCurseCardToThem":
            cats.append("COPY_CURSE")
    elif t == "ExileEffect":
        if m == "ExileSelf":
            cats.append("EXILE_SELF")
        elif m in ("ExileMyCards", "ExileMyCardsWithTag", "ExileMyMinions", "ExileMyCardsWithTypeID",
                   "ExileMyCards_BasedOnIntSO"):
            cats.append("EXILE_FRIENDLY")
        elif m in ("ExileTheirCards", "ExileTheirCardsWithTag", "ExileTheirMinions",
                   "ExileTheirCards_BasedOnIntSO"):
            cats.append("EXILE_ENEMY")
        elif m == "ExileRandomCards":
            cats.append("EXILE_RANDOM")
        elif m == "ExileCardsWithTag":
            cats.append("EXILE_TAG")
    elif t == "DeckSizeIncreaseEffect":
        cats.append("DECK_SIZE_UP")
    elif t == "HPMaxAlterEffect":
        if m.startswith("IncreaseMyHpMax"):
            cats.append("HP_MAX_UP_SELF")
        elif m.startswith("IncreaseTheirHpMax"):
            cats.append("HP_MAX_UP_OPPONENT")

    return cats


# -----------------------------------------------------------------------------
# Description parsing
# -----------------------------------------------------------------------------

def normalize_punctuation(text):
    # Replace common English punctuation used in descriptions with Chinese equivalents
    # for consistent parsing, but keep colons as markers.
    text = text.replace("；", ";")
    text = text.replace("，", ",")
    text = text.replace("：", ":")
    return text


def split_segments(desc):
    desc = normalize_punctuation(strip_tags(desc))
    # Split by ; or newline
    segs = re.split(r"[;\n]", desc)
    return [s.strip() for s in segs if s.strip()]


def extract_trigger_event(segment):
    """Infer GameEvent name from the trigger phrase of a segment."""
    if ":" in segment:
        trig = segment.split(":", 1)[0].strip()
    else:
        trig = ""
        # No explicit trigger phrase; infer from utility shop effects
        if re.search(r"卡位增加|生命值上限增加", segment):
            return "OnMeBought"
        return "OnMeRevealed"  # default

    patterns = [
        ("当敌方[诅咒]揭晓", "OnHostileCurseRevealed"),
        ("当敌方[诅咒]获得力量", "OnEnemyCurseCardGotPower"),
        ("当友方被埋葬", "OnFriendlyCardBuried"),
        ("友方被埋葬", "OnFriendlyCardBuried"),
        ("当卡被埋葬", "OnFriendlyCardBuried"),
        ("当友方被去除", "OnFriendlyCardExiled"),
        ("友方被去除", "OnFriendlyCardExiled"),
        ("当敌人受到伤害", "OnTheirPlayerTookDmg"),
        ("敌人受到伤害", "OnTheirPlayerTookDmg"),
        ("当友方获得力量", "OnFriendlyCardGotPower"),
        ("敌人被揭晓", "OnHostileRevealed"),
        ("洗牌后", "AfterShuffle"),
        ("被置顶", "OnMeStaged"),
        ("被埋葬", "OnMeBuried"),
        ("获得力量时", "OnMeGotStatusEffect"),
        ("揭晓", "OnMeRevealed"),
        ("每", "OnMeRevealed"),
    ]
    for kw, ev in patterns:
        if kw in trig:
            return ev
    return "OnMeRevealed"


def extract_expected_categories(segment):
    """Return list of expected semantic effect categories from an effect phrase."""
    cats = []
    eff = segment.split(":", 1)[1] if ":" in segment else segment
    eff = eff.strip()
    if not eff:
        return cats

    # Split effect phrase into clauses by comma/semicolon so cross-clause
    # keywords (e.g. "埋葬 ... , 增强 ... 敌方") are not mixed up.
    clauses = re.split(r"[,;]", eff)

    for clause in clauses:
        clause = clause.strip()
        if not clause:
            continue

        # Damage
        if re.search(r"造成\s*\d*\s*伤害|造成\s*\[力量\].*?伤害|伤害\s*x", clause):
            if re.search(r"对自己|自身", clause):
                cats.append("DAMAGE_SELF")
            else:
                cats.append("DAMAGE_OPPONENT")
        elif "对自己" in clause and "伤害" in clause:
            cats.append("DAMAGE_SELF")

        # Bury
        if re.search(r"埋葬\s*\d*\s*友方|埋葬所有友方", clause):
            cats.append("BURY_FRIENDLY")
        if re.search(r"埋葬\s*\d*\s*敌方", clause):
            cats.append("BURY_HOSTILE")
        if re.search(r"埋葬后\s*\d+\s*卡", clause):
            cats.append("BURY_NEXT")

        # Stage
        if re.search(r"置顶\s*\d*\s*友方|置顶自身", clause):
            cats.append("STAGE_FRIENDLY")
        if re.search(r"置顶\s*\d*\s*敌方|置顶力量最多的敌方", clause):
            cats.append("STAGE_HOSTILE")

        # Curse enhance
        if re.search(r"增强\s*(?:\d+\s*)?敌方\s*\[诅咒\](?:\s*\d+)?|增强敌方\[诅咒\]", clause):
            cats.append("ENHANCE_CURSE")
        if re.search(r"增强\s*(?:\d+\s*)?自身诅咒", clause):
            cats.append("ENHANCE_FRIENDLY_CURSE")
        if re.search(r"\[诅咒\].*?获得\s*\d*\s*力量", clause):
            cats.append("ENHANCE_CURSE")

        # Consume curse power
        if re.search(r"消耗敌方\[诅咒\].*?力量|敌方\[诅咒\]力量\s*-\s*\d+", clause):
            cats.append("CONSUME_CURSE_POWER")

        # Give status effect
        if re.search(r"给予\s*\d*\s*友方\s*\d*\s*力量|给予下\s*\d+\s*卡\s*\d*\s*力量|所有友方获得\s*\d*\s*力量|给予该友方", clause):
            cats.append("GIVE_STATUS_EFFECT")
        if re.search(r"获得\s*\d*\s*力量|获得\s*\d*\s*倍力量|翻倍.*?力量", clause):
            # "[诅咒]获得力量" is handled as curse enhance above
            if not re.search(r"\[诅咒\].*?获得\s*\d*\s*力量", clause):
                cats.append("GIVE_STATUS_EFFECT")

        # Consume status effect
        if re.search(r"去除\s*\d*\s*敌方\s*\d*\s*力量|消耗\s*\d+\s*力量", clause):
            cats.append("CONSUME_STATUS_EFFECT")

        # Transfer status effect
        if "转移" in clause and "力量" in clause:
            cats.append("TRANSFER_STATUS_EFFECT")

        # Add temp card / copy curse
        if re.search(r"生成\s*\d*\s*\[次元裂缝\]", clause):
            cats.append("ADD_CARD_FRIENDLY")
        if re.search(r"复制敌方\s*\d*\s*\[诅咒\]", clause):
            cats.append("COPY_CURSE")
        if "添加自身到卡组" in clause:
            cats.append("ADD_CARD_FRIENDLY")

        # Exile
        if re.search(r"放逐\s*\d*\s*友方", clause):
            cats.append("EXILE_FRIENDLY")
        if re.search(r"放逐\s*\d*\s*敌方", clause):
            cats.append("EXILE_ENEMY")
        if "去除自身" in clause or "放逐自身" in clause:
            cats.append("EXILE_SELF")

        # Utility
        if re.search(r"卡位增加", clause):
            cats.append("DECK_SIZE_UP")
        if re.search(r"生命值上限增加", clause):
            cats.append("HP_MAX_UP_SELF")

    return list(set(cats))


# -----------------------------------------------------------------------------
# Matching
# -----------------------------------------------------------------------------

COMPATIBLE_CATEGORIES = {
    "DAMAGE_OPPONENT": {"DAMAGE_OPPONENT"},
    "DAMAGE_SELF": {"DAMAGE_SELF"},
    "BURY_FRIENDLY": {"BURY_FRIENDLY", "BURY_TAG"},
    "BURY_HOSTILE": {"BURY_HOSTILE", "BURY_TAG"},
    "BURY_NEXT": {"BURY_NEXT"},
    "BURY_SELF": {"BURY_SELF"},
    "STAGE_FRIENDLY": {"STAGE_FRIENDLY", "STAGE_MOST_STATUS"},
    "STAGE_HOSTILE": {"STAGE_HOSTILE", "STAGE_MOST_STATUS"},
    "ENHANCE_CURSE": {"ENHANCE_CURSE"},
    "ENHANCE_FRIENDLY_CURSE": {"ENHANCE_FRIENDLY_CURSE"},
    "CONSUME_CURSE_POWER": {"CONSUME_CURSE_POWER"},
    "GIVE_STATUS_EFFECT": {"GIVE_STATUS_EFFECT"},
    "CONSUME_STATUS_EFFECT": {"CONSUME_STATUS_EFFECT"},
    "TRANSFER_STATUS_EFFECT": {"TRANSFER_STATUS_EFFECT"},
    "ADD_CARD_FRIENDLY": {"ADD_CARD_FRIENDLY"},
    "ADD_CARD_ENEMY": {"ADD_CARD_ENEMY"},
    "COPY_CURSE": {"COPY_CURSE"},
    "EXILE_FRIENDLY": {"EXILE_FRIENDLY", "EXILE_TAG"},
    "EXILE_ENEMY": {"EXILE_ENEMY", "EXILE_TAG"},
    "EXILE_SELF": {"EXILE_SELF"},
    "EXILE_RANDOM": {"EXILE_RANDOM"},
    "DECK_SIZE_UP": {"DECK_SIZE_UP"},
    "HP_MAX_UP_SELF": {"HP_MAX_UP_SELF"},
}


def categories_match(expected_cat, actual_cats):
    """Check whether any actual category satisfies the expected category."""
    allowed = COMPATIBLE_CATEGORIES.get(expected_cat, {expected_cat})
    return bool(set(actual_cats).intersection(allowed))


def check_card(card):
    mismatches = []
    desc = card["desc"]
    segments = split_segments(desc)

    for seg in segments:
        trigger = extract_trigger_event(seg)
        expected_cats = extract_expected_categories(seg)
        if not expected_cats:
            # No recognizable effect in this segment (e.g. pure trigger like "萦绕")
            continue

        # Find listener bindings for this trigger event
        matching_listeners = [lst for lst in card["listeners"] if lst["event"] == trigger]
        if not matching_listeners:
            mismatches.append({
                "segment": seg,
                "trigger": trigger,
                "expected": expected_cats,
                "issue": "缺少对应触发事件的 Listener",
                "actual_listeners": [],
            })
            continue

        # Collect all actual effect categories from those listeners
        actual_cats = []
        for lst in matching_listeners:
            for call in lst["effects"]:
                actual_cats.extend(method_categories(call))
        actual_cats = list(set(actual_cats))

        # Check each expected category
        for exp_cat in expected_cats:
            if not categories_match(exp_cat, actual_cats):
                mismatches.append({
                    "segment": seg,
                    "trigger": trigger,
                    "expected": [exp_cat],
                    "issue": "效果类型不匹配",
                    "actual_listeners": matching_listeners,
                })
                break  # one mismatch per segment is enough

    # Also detect orphan listeners: event not described by any segment
    described_triggers = set()
    for seg in segments:
        described_triggers.add(extract_trigger_event(seg))

    orphan_listeners = []
    for lst in card["listeners"]:
        if lst["event"] not in described_triggers:
            orphan_listeners.append(lst)

    return mismatches, orphan_listeners


def listener_summary(lst):
    lines = ["- `" + lst["container"] + "` (" + lst["event"] + ")"]
    for call in lst["effects"]:
        lines.append("  - " + call["type"] + "->" + call["method"] + "(" + str(call["arg"]) + ")")
    return "\n".join(lines)


def build_report(cards):
    lines = []
    lines.append("# 卡片描述与 GameEventListener Response 对应检查报告")
    lines.append("")
    lines.append("**检查范围**：`Assets/Prefabs/Cards/3.0 no cost (current)` 下全部卡片")
    lines.append("")
    lines.append("**检查逻辑**：")
    lines.append("1. 将 `cardDesc` 拆分为独立触发段落。")
    lines.append("2. 根据段落推断期望的触发事件与效果语义类别（如 `造成 X 伤害` → 伤害、`置顶友方` → 置顶友方等）。")
    lines.append("3. 读取每个 `GameEventListener` 的触发事件及其 `Response` 实际调用的 `CostNEffectContainer`，并提取 `effectEvent` 方法。")
    lines.append("4. 若某段描述的效果在对应事件的 Listener/Container 中找不到匹配的方法，则标记为问题。")
    lines.append("")

    issue_cards = []
    for card in cards:
        mismatches, orphans = check_card(card)
        if mismatches or orphans:
            issue_cards.append((card, mismatches, orphans))

    total = len(cards)
    ok = total - len(issue_cards)
    lines.append("## 摘要")
    lines.append("")
    lines.append("| 项目 | 数量 |")
    lines.append("|---|---|")
    lines.append("| 检查卡片总数 | " + str(total) + " |")
    lines.append("| 无问题 | " + str(ok) + " |")
    lines.append("| 存在疑似不匹配 | " + str(len(issue_cards)) + " |")
    lines.append("")

    if not issue_cards:
        lines.append("## 结果")
        lines.append("")
        lines.append("所有卡片的描述与 Listener Response 均匹配，未发现明显不匹配。")
        lines.append("")
        return "\n".join(lines)

    lines.append("## 疑似不匹配卡片")
    lines.append("")

    for idx, (card, mismatches, orphans) in enumerate(issue_cards, 1):
        lines.append("### " + str(idx) + ". " + card["name"])
        lines.append("")
        lines.append("**路径**：`" + card["path"] + "`")
        lines.append("")
        lines.append("**描述**：")
        lines.append("```")
        lines.append(card["desc"])
        lines.append("```")
        lines.append("")

        if mismatches:
            lines.append("**描述段落与 Response 不匹配**：")
            lines.append("")
            lines.append("| 描述段落 | 期望事件 | 期望效果 | 问题 | 实际 Container |")
            lines.append("|---|---|---|---|---|")
            for m in mismatches:
                actual = ""
                if m["actual_listeners"]:
                    actual = "<br>".join([lst["container"] + " (" + lst["event"] + "): " +
                                          ", ".join([call["type"] + "->" + call["method"] for call in lst["effects"]])
                                          for lst in m["actual_listeners"]])
                else:
                    actual = "无"
                lines.append("| " + m["segment"] + " | " + m["trigger"] + " | " + ", ".join(m["expected"]) + " | " + m["issue"] + " | " + actual + " |")
            lines.append("")

        if orphans:
            lines.append("**未在描述中体现的 Listener**：")
            lines.append("")
            for lst in orphans:
                lines.append(listener_summary(lst))
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("**注意**：本报告基于关键词与方法名的语义匹配，复杂表述、多效果组合或特殊逻辑可能需要人工复核。")
    lines.append("")
    return "\n".join(lines)


def main():
    cards = parse_log(INPUT_PATH)
    report = build_report(cards)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(report)
    print("Report written to:", OUTPUT_PATH)
    print("Cards checked:", len(cards))


if __name__ == "__main__":
    main()
